### ISSUE TITLE
Mean method not working

### ISSUE THREAD

**Issue by karhincheong** [karhincheong/mat#3]
The mean feature is somehow not working properly
```
➜ python comat.py stats 1 2 3 mean                                                      
Traceback (most recent call last):
  File "/home/karhin/Desktop/dev/comat/comat.py", line 28, in <module>
    app()
  File "/home/karhin/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/karhin/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/karhin/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/karhin/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karhin/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karhin/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/karhin/.local/lib/python3.10/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/karhin/Desktop/dev/comat/comat.py", line 24, in stats
    print(mean_from_array(arr))
  File "/home/karhin/Desktop/dev/comat/algorithms/statistics.py", line 25, in mean_from_array
    for i in range(0, len(arr)):
TypeError: range() takes 1 positional argument but 2 were given
```

**Comment by karhincheong** [comment]
@cytronicoder help

**Comment by zeyuyaoy** [comment]
Try `for i in range(len(arr))` in `algorithms/statistics.py`. Python automatically passes self to the class method when it is called.

**Comment by karhincheong** [comment]
Turns out it was a conflict between the `range` keyword and the `range` function defined in `algorithms/statistics.py`
Resolved.
